### ISSUE TITLE
Feature request: custom target WP for sdr-csc mode

### ISSUE THREAD

**Issue by ikrasnopeev** [dantmnf/MHC2#11]
Hi  dantmnf,

First of all, great thanks for an awesome utility. It literally saved me with my work Lenovo laptop's WG crap-EDID display I struggled more that a year!

Now I'm facing another challenge calibrating another laptop's OLED display. I'm able to calibrate it to sRGB with my i1Pro2 and then built decent SDR profile with MHC2Gen. The _tiny_ problem I have, seems to be related to LED-OLED technologies difference. For some reason my eyes contradict i1Pro measurements and tell me white color noticeable differs from what they expect to be "6500K white". At least while comparing with two hardware-calibrated external IPS monitors. 

I previously experienced similar issue when I played with LG OLED monitor and the obvious solution I ended up with was to try to calibrate OLED to some custom WP which **looks** like IPS's 6500K. When I tried to do this now, I ended up with target WP to be about 6800K (0.3094x0.3186). 

I stared with sRGB preset in DisplayCAL, changed WP to above value and was able to achieve ~6850K (0.3086x0.3176), which is pretty close and now white looks almost the same as on IPS displays. Obviously with wide gamut.

But as soon as I convert DisplayCAL's profile to sdr using "MHC2Gen sdr-csc..." command and apply it, white point is changed back to ~6500K (0.3141x0.3274) which gives me different white perception again.

I wonder if this is some Windows Color Pipeline/MHC limitation? Or is it possible to add custom target WP while doing such profile conversion?

Thanks!
Igor

**Comment by dantmnf** [comment]
This also applies to ACM mode. We need to find an approach to keep the calibrated white point.
