### ISSUE TITLE
Still can’t see “Automatically manage color for apps” in the setting

### ISSUE THREAD

**Issue by jiabaoyu** [dantmnf/MHC2#5]
Tried appending the item in registry like blew and rebooted windows.

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"EnableAcmSupportDeveloperPreview"=dword:00000001
```

Still can’t see “Automatically manage color for apps” in the setting. 

Sysinfo:
```
CPU Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz
RAM 32.0 GB 
GPU	RTX2080
Monitor LG 34WK95U
Windows 11 22H2 22621.755 Windows Feature Experience Pack 1000.22636.1000.0
```

**Comment by dantmnf** [comment]
Your display seems to be HDR-capable: https://www.lg.com/us/monitors/lg-34WK95U-W-ultrawide-monitor

SDR Advanced Color is currently unavailable on HDR-capable display, nothing can do on my side.

**Comment by jiabaoyu** [comment]
> Your display seems to be HDR-capable: https://www.lg.com/us/monitors/lg-34WK95U-W-ultrawide-monitor
> 
> SDR Advanced Color is currently unavailable on HDR-capable display, nothing can do on my side.

While I am using it in its SDR mode.

**Comment by aufkrawall** [comment]
> While I am using it in its SDR mode.

Edit your monitor's EDID with CRU by un-ticking colorspaces checkboxes in CTA-861 extension block -> Colorimetry:
https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU

Then HDR should become unavailable, which makes the clamp toggle appear.

**Comment by jiabaoyu** [comment]
> > While I am using it in its SDR mode.
> 
> Edit your monitor's EDID with CRU by un-ticking colorspaces checkboxes in CTA-861 extension block -> Colorimetry: https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU
> 
> Then HDR should become unavailable, which makes the clamp toggle appear.

This did work! Thanks!

To others who would try this method, I have a warning for you:
The ACM will render the srgb contents properly on wide gamut display, apart from some microsoft store app like affinity photo will be forced rendering in srgb even if I tick the ["Use legacy display ICC color management." in the executable's properties](https://learn.microsoft.com/en-us/windows/win32/wcs/advanced-color-icc-profiles#enabling-the-display-icc-compatibility-helper). (On the other hand when Photoshop.exe's ticked, and it works flawlessly.) I am not sure whether the installer version of affinity photo will be OK or not. Will investigate further.

**Comment by jiabaoyu** [comment]
As a follow up, I tried install GIMP using its official installer it worked flawlessly. Then I uninstalled it and reinstalled from Microsoft Store, it also works without any tweaks. So it's the affinity apps' problem, at least the store versions.

**Comment by aufkrawall** [comment]
I don't have access to that Affinity Photo app, but so far store apps (e.g. Amazon Prime or Windows Photo) seem to work fine for me with the clamp. I use an SDR ACM profile generated by @dantmnf 's fantastic tool for full calibration (with great results, according to DisplayCal verification).

**Comment by jiabaoyu** [comment]
> I don't have access to that Affinity Photo app, but so far store apps (e.g. Amazon Prime or Windows Photo) seem to work fine for me with the clamp. I use an SDR ACM profile generated by @dantmnf 's fantastic tool for full calibration (with great results, according to DisplayCal verification).

I've encountered a problem right after I enabled ACM, the profile generated by the LG calibration software works like a charm, somehow after the display auto black out and waken up, the colors seem to be washed out.
I haven't done any research on his tool. What's that for?

**Comment by jiabaoyu** [comment]
> > I don't have access to that Affinity Photo app, but so far store apps (e.g. Amazon Prime or Windows Photo) seem to work fine for me with the clamp. I use an SDR ACM profile generated by @dantmnf 's fantastic tool for full calibration (with great results, according to DisplayCal verification).
> 
> I've encountered a problem right after I enabled ACM, the profile generated by the LG calibration software works like a charm, somehow after the display auto black out and waken up, the colors seem to be washed out. I haven't done any research on his tool. What's that for?

After some experiments, toggling the ACM option off and on again (maybe once or several times), the washed-out behavior will temporally gone.

**Comment by aufkrawall** [comment]
Seems to be a bug of that API when e.g. driver installers restart the graphics drivers.

**Comment by jiabaoyu** [comment]
> Seems to be a bug of that API when e.g. driver installers restart the graphics drivers, looks like clamp is applied more than once then.

My setup is I use the i1 display pro with the LG's proprietary hardware calibration software which writes 3D lut directly into the monitor and leaves an informational icc in the system for the icc aware apps to be aware of the display's characteristics.
So do I need to proceed to use the MHC2 to do something?

**Comment by dantmnf** [comment]
It looks like you are doing double correction. You can use 3D LUT to correct cross-channel non-linear characteristics but keep its native gamut, then SDR ACM can give even better accuracy. Or simply use either calibration approach, but not both at the same time.

**Comment by jiabaoyu** [comment]
> It looks like you are doing double correction. You can use 3D LUT to correct cross-channel non-linear characteristics but keep its native gamut, then SDR ACM can give even better accuracy. Or simply use either calibration approach, but not both at the same time.

I don't quite understand what you mean. While for the most time this works really well. BTW I'm calibrating the display to  its native gamut (not restricting to any know gamut).

**Comment by dantmnf** [comment]
OK, I understand it now.

Theoretically if your display have correct chromaticity values in EDID and is calibrated to sRGB transfer, it will automagically work like a charm. Maybe there are some glitches in EDID reading/parsing, you can try mhc2gen with the generated informational ICC.

**Comment by jiabaoyu** [comment]
> OK, I understand it now.
> 
> Theoretically if your display have correct chromaticity values in EDID and is calibrated to sRGB transfer, it will automagically work like a charm. Maybe there are some glitches in EDID reading/parsing, you can try mhc2gen with the generated informational ICC.

Sorry, there's a misunderstanding. If I calibrate the display to srgb, I wouldn't take any advantage of the new ACM and it's meaningless to get such a long way here.
My display's native gamut is about 98% P3. I just calibrate it to its native gamut with gamma2.2 and D65. The display has a feature that could store the 3D lut inside the display's "OS", so that if I calibrate it the some standard gamut space that isn't surpass 100% P3 to much e.g. display P3, to any PC or Mac connected to, the user could just set the OS a standard display P3 icc profile. 
However I don't know if the calibration software would modify the EDID info. How do I know if there's modification?

**Comment by dantmnf** [comment]
> If I calibrate the display to srgb, I wouldn't take any advantage of the new ACM and it's meaningless to get such a long way here.

I mean the sRGB transfer function (gamma), not the sRGB / Rec. 709 gamut.

**Comment by jiabaoyu** [comment]
> > If I calibrate the display to srgb, I wouldn't take any advantage of the new ACM and it's meaningless to get such a long way here.
> 
> I mean the sRGB transfer function (gamma), not the sRGB / Rec. 709 gamut.

Great! So there's no misunderstood any more. I still don't know what's your tool's usage for?

**Comment by dantmnf** [comment]
In your case, an MHC ICC profile can be used to override EDID info.

**Comment by jiabaoyu** [comment]
I just experienced that when the PC or monitor awoken from sleep mode, the ACM will probably break (either applies twice or de-applied twice).
I have to take a procedure that go to settings and "disable and enable" twice to make sure ACM works again.

**Comment by jiabaoyu** [comment]
> In your case, an MHC ICC profile can be used to override EDID info.

I've already used @aufkrawall 's suggested CRU. Otherwise the ACM option wouldn't appear in the settings.
